In [ ]:
#!/usr/bin/env python3
#Lapan text book Chapter 6, example 1
import gym
import collections
#from gym.utils.play import play
#from tensorboardX import SummaryWriter
import numpy as np


ENV_NAME = "FrozenLake-v1"
TEST_EPISODES = 50


'''Things to try
1. Epsilon greedy action (set exploration_prob=0.1) v. random action selection policy (set exploration_prob = 1)
2. Learning rate
'''


In [ ]:
class QLearning:
    def __init__(self, num_states, num_actions, learning_rate=0.1, discount_factor=1, exploration_prob=1):


    def choose_action(self, state, random_action):

    def update_q_table(self, state, action, next_state, reward):

    def update_rates(self, iteration):

    def play_episode(self, env): #play learned policy and return total reward

    def get_q_table(self):


In [ ]:
if __name__ == "__main__":
    env = gym.make(ENV_NAME)
    #env =gym.make(ENV_NAME, render_mode="human")
    ql_agent = QLearning(env.observation_space.n, env.action_space.n)
    #writer = SummaryWriter(comment="QL_frozen lake")
    NUM_EPISODES = 10000
    best_reward = 0.0
    for episode in range(NUM_EPISODES):
        state = env.reset()
        done = False

        while not done:
          FILL#Choose an action
          FILL # Take the chosen action and observe the next state and reward
          FILL #update Q-factors

          state = next_state

        # Evaluate the learned Q-table
        total_reward = 0
        for _ in range(TEST_EPISODES):
            total_reward += ql_agent.play_episode(env)

        average_reward = total_reward / TEST_EPISODES
        #writer.add_scalar("reward", average_reward, episode)
        if average_reward > best_reward:
            print("Best reward updated %.3f -> %.3f" % (
                best_reward, average_reward))
            best_reward = average_reward
        if average_reward > 0.80:
            print("Solved in %d iterations!" % episode)
            break

    # Evaluate the learned Q-table
    #env = gym.wrappers.Monitor(env, "recording")
    q_table=ql_agent.get_q_table()
    print(q_table)
    #writer.close()
#tensorboard --logdir runs

Best reward updated 0.000 -> 0.600
Best reward updated 0.600 -> 0.680
Best reward updated 0.680 -> 0.700
Best reward updated 0.700 -> 0.760
Best reward updated 0.760 -> 0.780
Best reward updated 0.780 -> 0.820
Solved in 752 iterations!
[[0.04271466 0.03947953 0.04066421 0.03817192]
 [0.02445388 0.02473359 0.02765454 0.03659854]
 [0.04007641 0.03221046 0.04595537 0.02180754]
 [0.01514859 0.01395877 0.00324801 0.01463811]
 [0.04559427 0.02557157 0.02368749 0.02652989]
 [0.         0.         0.         0.        ]
 [0.03748408 0.08034135 0.05540576 0.00509174]
 [0.         0.         0.         0.        ]
 [0.02616992 0.04477712 0.04982931 0.0575126 ]
 [0.04724975 0.10351466 0.07642008 0.06180346]
 [0.15716755 0.10813633 0.08199949 0.04677679]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.04844163 0.13608532 0.14128762 0.12683532]
 [0.1095055  0.38469979 0.34874781 0.35370361]
 [0.         0.         0.         0.        ]]
